/**
 * hsk.js — New HSK (2021) vocabulary, Levels 1–6
 * Each entry: { zh, pinyin, en }
 * Loaded by index.html before app.js
 */

const HSK_DATA = {

  1: [
    { zh:"爱",     pinyin:"ài",           en:"to love" },
    { zh:"八",     pinyin:"bā",           en:"eight" },
    { zh:"爸爸",   pinyin:"bàba",         en:"dad, father" },
    { zh:"杯子",   pinyin:"bēizi",        en:"cup, glass" },
    { zh:"北京",   pinyin:"Běijīng",      en:"Beijing" },
    { zh:"本",     pinyin:"běn",          en:"(measure word for books)" },
    { zh:"不客气", pinyin:"bù kèqi",      en:"you're welcome" },
    { zh:"菜",     pinyin:"cài",          en:"dish, vegetable" },
    { zh:"茶",     pinyin:"chá",          en:"tea" },
    { zh:"吃",     pinyin:"chī",          en:"to eat" },
    { zh:"出租车", pinyin:"chūzūchē",     en:"taxi" },
    { zh:"打电话", pinyin:"dǎ diànhuà",   en:"to make a phone call" },
    { zh:"大",     pinyin:"dà",           en:"big, large" },
    { zh:"的",     pinyin:"de",           en:"(possessive particle)" },
    { zh:"弟弟",   pinyin:"dìdi",         en:"younger brother" },
    { zh:"点",     pinyin:"diǎn",         en:"o'clock; a little" },
    { zh:"电脑",   pinyin:"diànnǎo",      en:"computer" },
    { zh:"电视",   pinyin:"diànshì",      en:"television" },
    { zh:"电影",   pinyin:"diànyǐng",     en:"movie, film" },
    { zh:"东西",   pinyin:"dōngxi",       en:"thing, stuff" },
    { zh:"都",     pinyin:"dōu",          en:"all, both" },
    { zh:"读",     pinyin:"dú",           en:"to read" },
    { zh:"对不起", pinyin:"duìbuqǐ",      en:"sorry, excuse me" },
    { zh:"多",     pinyin:"duō",          en:"many, much" },
    { zh:"多少",   pinyin:"duōshao",      en:"how many, how much" },
    { zh:"儿子",   pinyin:"érzi",         en:"son" },
    { zh:"二",     pinyin:"èr",           en:"two" },
    { zh:"饭店",   pinyin:"fàndiàn",      en:"restaurant, hotel" },
    { zh:"飞机",   pinyin:"fēijī",        en:"airplane" },
    { zh:"分钟",   pinyin:"fēnzhōng",     en:"minute" },
    { zh:"高兴",   pinyin:"gāoxìng",      en:"happy, pleased" },
    { zh:"个",     pinyin:"gè",           en:"(general measure word)" },
    { zh:"工作",   pinyin:"gōngzuò",      en:"work, job" },
    { zh:"狗",     pinyin:"gǒu",          en:"dog" },
    { zh:"汉语",   pinyin:"Hànyǔ",        en:"Chinese (language)" },
    { zh:"好",     pinyin:"hǎo",          en:"good, well" },
    { zh:"喝",     pinyin:"hē",           en:"to drink" },
    { zh:"和",     pinyin:"hé",           en:"and, with" },
    { zh:"很",     pinyin:"hěn",          en:"very" },
    { zh:"后面",   pinyin:"hòumian",      en:"behind, back" },
    { zh:"回",     pinyin:"huí",          en:"to return" },
    { zh:"会",     pinyin:"huì",          en:"can, be able to" },
    { zh:"几",     pinyin:"jǐ",           en:"how many (small number)" },
    { zh:"家",     pinyin:"jiā",          en:"home, family" },
    { zh:"叫",     pinyin:"jiào",         en:"to be called, to call" },
    { zh:"今天",   pinyin:"jīntiān",      en:"today" },
    { zh:"九",     pinyin:"jiǔ",          en:"nine" },
    { zh:"开",     pinyin:"kāi",          en:"to open, to drive" },
    { zh:"看",     pinyin:"kàn",          en:"to look, to watch" },
    { zh:"看见",   pinyin:"kànjiàn",      en:"to see, to catch sight of" },
    { zh:"块",     pinyin:"kuài",         en:"yuan (currency); piece" },
    { zh:"来",     pinyin:"lái",          en:"to come" },
    { zh:"老师",   pinyin:"lǎoshī",       en:"teacher" },
    { zh:"冷",     pinyin:"lěng",         en:"cold" },
    { zh:"里",     pinyin:"lǐ",           en:"inside, in" },
    { zh:"六",     pinyin:"liù",          en:"six" },
    { zh:"妈妈",   pinyin:"māma",         en:"mom, mother" },
    { zh:"吗",     pinyin:"ma",           en:"(yes/no question particle)" },
    { zh:"猫",     pinyin:"māo",          en:"cat" },
    { zh:"没关系", pinyin:"méi guānxi",   en:"it doesn't matter, never mind" },
    { zh:"没有",   pinyin:"méiyǒu",       en:"don't have, there isn't" },
    { zh:"米饭",   pinyin:"mǐfàn",        en:"cooked rice" },
    { zh:"明天",   pinyin:"míngtiān",     en:"tomorrow" },
    { zh:"名字",   pinyin:"míngzi",       en:"name" },
    { zh:"哪",     pinyin:"nǎ",           en:"which" },
    { zh:"那",     pinyin:"nà",           en:"that" },
    { zh:"你",     pinyin:"nǐ",           en:"you" },
    { zh:"年",     pinyin:"nián",         en:"year" },
    { zh:"女儿",   pinyin:"nǚ'ér",        en:"daughter" },
    { zh:"朋友",   pinyin:"péngyou",      en:"friend" },
    { zh:"漂亮",   pinyin:"piàoliang",    en:"beautiful, pretty" },
    { zh:"苹果",   pinyin:"píngguǒ",      en:"apple" },
    { zh:"七",     pinyin:"qī",           en:"seven" },
    { zh:"钱",     pinyin:"qián",         en:"money" },
    { zh:"请",     pinyin:"qǐng",         en:"please; to invite" },
    { zh:"去",     pinyin:"qù",           en:"to go" },
    { zh:"热",     pinyin:"rè",           en:"hot" },
    { zh:"人",     pinyin:"rén",          en:"person, people" },
    { zh:"认识",   pinyin:"rènshi",       en:"to know (a person)" },
    { zh:"三",     pinyin:"sān",          en:"three" },
    { zh:"商店",   pinyin:"shāngdiàn",    en:"shop, store" },
    { zh:"上",     pinyin:"shàng",        en:"on, above, up" },
    { zh:"上午",   pinyin:"shàngwǔ",      en:"morning, a.m." },
    { zh:"少",     pinyin:"shǎo",         en:"few, little" },
    { zh:"谁",     pinyin:"shéi",         en:"who" },
    { zh:"什么",   pinyin:"shénme",       en:"what" },
    { zh:"生日",   pinyin:"shēngrì",      en:"birthday" },
    { zh:"是",     pinyin:"shì",          en:"to be (am/is/are)" },
    { zh:"书",     pinyin:"shū",          en:"book" },
    { zh:"水",     pinyin:"shuǐ",         en:"water" },
    { zh:"水果",   pinyin:"shuǐguǒ",      en:"fruit" },
    { zh:"睡觉",   pinyin:"shuìjiào",     en:"to sleep" },
    { zh:"说",     pinyin:"shuō",         en:"to speak, to say" },
    { zh:"四",     pinyin:"sì",           en:"four" },
    { zh:"岁",     pinyin:"suì",          en:"years old (age)" },
    { zh:"他",     pinyin:"tā",           en:"he, him" },
    { zh:"她",     pinyin:"tā",           en:"she, her" },
    { zh:"太",     pinyin:"tài",          en:"too, extremely" },
    { zh:"天气",   pinyin:"tiānqì",       en:"weather" },
    { zh:"听",     pinyin:"tīng",         en:"to listen, to hear" },
    { zh:"同学",   pinyin:"tóngxué",      en:"classmate" },
    { zh:"我",     pinyin:"wǒ",           en:"I, me" },
    { zh:"我们",   pinyin:"wǒmen",        en:"we, us" },
    { zh:"五",     pinyin:"wǔ",           en:"five" },
    { zh:"下午",   pinyin:"xiàwǔ",        en:"afternoon, p.m." },
    { zh:"下雨",   pinyin:"xià yǔ",       en:"to rain" },
    { zh:"先生",   pinyin:"xiānsheng",    en:"Mr., husband" },
    { zh:"现在",   pinyin:"xiànzài",      en:"now, at present" },
    { zh:"想",     pinyin:"xiǎng",        en:"to want, to think" },
    { zh:"小",     pinyin:"xiǎo",         en:"small, little" },
    { zh:"小姐",   pinyin:"xiǎojiě",      en:"Miss, young woman" },
    { zh:"谢谢",   pinyin:"xièxie",       en:"thank you" },
    { zh:"星期",   pinyin:"xīngqī",       en:"week" },
    { zh:"学生",   pinyin:"xuésheng",     en:"student" },
    { zh:"学习",   pinyin:"xuéxí",        en:"to study, to learn" },
    { zh:"学校",   pinyin:"xuéxiào",      en:"school" },
    { zh:"一",     pinyin:"yī",           en:"one" },
    { zh:"一点儿", pinyin:"yìdiǎnr",      en:"a little, a bit" },
    { zh:"衣服",   pinyin:"yīfu",         en:"clothes" },
    { zh:"医生",   pinyin:"yīshēng",      en:"doctor" },
    { zh:"医院",   pinyin:"yīyuàn",       en:"hospital" },
    { zh:"椅子",   pinyin:"yǐzi",         en:"chair" },
    { zh:"一起",   pinyin:"yìqǐ",         en:"together" },
    { zh:"有",     pinyin:"yǒu",          en:"to have, there is" },
    { zh:"鱼",     pinyin:"yú",           en:"fish" },
    { zh:"月",     pinyin:"yuè",          en:"month, moon" },
    { zh:"再见",   pinyin:"zàijiàn",      en:"goodbye" },
    { zh:"在",     pinyin:"zài",          en:"at, in, on; to be at" },
    { zh:"怎么",   pinyin:"zěnme",        en:"how, why" },
    { zh:"怎么样", pinyin:"zěnmeyàng",    en:"how is it, what about" },
    { zh:"这",     pinyin:"zhè",          en:"this" },
    { zh:"中国",   pinyin:"Zhōngguó",     en:"China" },
    { zh:"中午",   pinyin:"zhōngwǔ",      en:"noon, midday" },
    { zh:"住",     pinyin:"zhù",          en:"to live, to stay" },
    { zh:"桌子",   pinyin:"zhuōzi",       en:"table, desk" },
    { zh:"坐",     pinyin:"zuò",          en:"to sit, to travel by" },
    { zh:"做",     pinyin:"zuò",          en:"to do, to make" },
    { zh:"昨天",   pinyin:"zuótiān",      en:"yesterday" },
  ],

  2: [
    { zh:"吧",     pinyin:"ba",           en:"(suggestion particle)" },
    { zh:"白",     pinyin:"bái",          en:"white" },
    { zh:"百",     pinyin:"bǎi",          en:"hundred" },
    { zh:"帮助",   pinyin:"bāngzhù",      en:"to help, assistance" },
    { zh:"报纸",   pinyin:"bàozhǐ",       en:"newspaper" },
    { zh:"比",     pinyin:"bǐ",           en:"compared to, than" },
    { zh:"别",     pinyin:"bié",          en:"don't; other" },
    { zh:"宾馆",   pinyin:"bīnguǎn",      en:"hotel" },
    { zh:"长",     pinyin:"cháng",        en:"long" },
    { zh:"唱歌",   pinyin:"chàng gē",     en:"to sing (a song)" },
    { zh:"出",     pinyin:"chū",          en:"to go out, to exit" },
    { zh:"穿",     pinyin:"chuān",        en:"to wear, to put on" },
    { zh:"次",     pinyin:"cì",           en:"time, occurrence" },
    { zh:"从",     pinyin:"cóng",         en:"from" },
    { zh:"错",     pinyin:"cuò",          en:"wrong, mistaken" },
    { zh:"打",     pinyin:"dǎ",           en:"to hit, to play (sport)" },
    { zh:"大家",   pinyin:"dàjiā",        en:"everyone, everybody" },
    { zh:"但是",   pinyin:"dànshì",       en:"but, however" },
    { zh:"到",     pinyin:"dào",          en:"to arrive, to reach" },
    { zh:"得",     pinyin:"de",           en:"(result complement particle)" },
    { zh:"等",     pinyin:"děng",         en:"to wait; etc." },
    { zh:"第一",   pinyin:"dì yī",        en:"first, number one" },
    { zh:"懂",     pinyin:"dǒng",         en:"to understand" },
    { zh:"对",     pinyin:"duì",          en:"correct, right" },
    { zh:"房间",   pinyin:"fángjiān",     en:"room" },
    { zh:"非常",   pinyin:"fēicháng",     en:"very, extremely" },
    { zh:"服务员", pinyin:"fúwùyuán",     en:"waiter, service staff" },
    { zh:"告诉",   pinyin:"gàosu",        en:"to tell, to inform" },
    { zh:"哥哥",   pinyin:"gēge",         en:"older brother" },
    { zh:"给",     pinyin:"gěi",          en:"to give; for" },
    { zh:"公共汽车",pinyin:"gōnggòng qìchē",en:"bus" },
    { zh:"公司",   pinyin:"gōngsī",       en:"company, firm" },
    { zh:"贵",     pinyin:"guì",          en:"expensive, noble" },
    { zh:"过",     pinyin:"guò",          en:"to pass, to cross; (past exp. particle)" },
    { zh:"还",     pinyin:"hái",          en:"also, still, yet" },
    { zh:"孩子",   pinyin:"háizi",        en:"child" },
    { zh:"好吃",   pinyin:"hǎochī",       en:"delicious, tasty" },
    { zh:"黑",     pinyin:"hēi",          en:"black" },
    { zh:"红",     pinyin:"hóng",         en:"red" },
    { zh:"欢迎",   pinyin:"huānyíng",     en:"to welcome, welcome" },
    { zh:"还是",   pinyin:"háishi",       en:"or (in questions); still" },
    { zh:"火车站", pinyin:"huǒchēzhàn",   en:"train station" },
    { zh:"机场",   pinyin:"jīchǎng",      en:"airport" },
    { zh:"鸡蛋",   pinyin:"jīdàn",        en:"egg" },
    { zh:"件",     pinyin:"jiàn",         en:"(measure word for clothing/matters)" },
    { zh:"教室",   pinyin:"jiàoshì",      en:"classroom" },
    { zh:"姐姐",   pinyin:"jiějie",       en:"older sister" },
    { zh:"介绍",   pinyin:"jièshào",      en:"to introduce" },
    { zh:"进",     pinyin:"jìn",          en:"to enter, to go in" },
    { zh:"近",     pinyin:"jìn",          en:"near, close" },
    { zh:"就",     pinyin:"jiù",          en:"then, just, exactly" },
    { zh:"觉得",   pinyin:"juéde",        en:"to feel, to think" },
    { zh:"咖啡",   pinyin:"kāfēi",        en:"coffee" },
    { zh:"开始",   pinyin:"kāishǐ",       en:"to start, to begin" },
    { zh:"考试",   pinyin:"kǎoshì",       en:"exam, to take an exam" },
    { zh:"可以",   pinyin:"kěyǐ",         en:"can, may" },
    { zh:"课",     pinyin:"kè",           en:"class, lesson" },
    { zh:"快",     pinyin:"kuài",         en:"fast, quick" },
    { zh:"快乐",   pinyin:"kuàilè",       en:"happy, joyful" },
    { zh:"离",     pinyin:"lí",           en:"away from, from" },
    { zh:"两",     pinyin:"liǎng",        en:"two (of something)" },
    { zh:"了解",   pinyin:"liǎojiě",      en:"to understand, to know about" },
    { zh:"零",     pinyin:"líng",         en:"zero" },
    { zh:"路",     pinyin:"lù",           en:"road, path" },
    { zh:"旅游",   pinyin:"lǚyóu",        en:"to travel, tourism" },
    { zh:"卖",     pinyin:"mài",          en:"to sell" },
    { zh:"慢",     pinyin:"màn",          en:"slow" },
    { zh:"忙",     pinyin:"máng",         en:"busy" },
    { zh:"每",     pinyin:"měi",          en:"every, each" },
    { zh:"妹妹",   pinyin:"mèimei",       en:"younger sister" },
    { zh:"门",     pinyin:"mén",          en:"door, gate" },
    { zh:"面条",   pinyin:"miàntiáo",     en:"noodles" },
    { zh:"男",     pinyin:"nán",          en:"male, man" },
    { zh:"难",     pinyin:"nán",          en:"difficult, hard" },
    { zh:"您",     pinyin:"nín",          en:"you (formal/polite)" },
    { zh:"牛奶",   pinyin:"niúnǎi",       en:"milk" },
    { zh:"女",     pinyin:"nǚ",           en:"female, woman" },
    { zh:"旁边",   pinyin:"pángbiān",     en:"beside, next to" },
    { zh:"跑步",   pinyin:"pǎo bù",       en:"to run, jogging" },
    { zh:"便宜",   pinyin:"piányí",       en:"cheap, inexpensive" },
    { zh:"票",     pinyin:"piào",         en:"ticket" },
    { zh:"妻子",   pinyin:"qīzi",         en:"wife" },
    { zh:"起床",   pinyin:"qǐ chuáng",    en:"to get up, to get out of bed" },
    { zh:"千",     pinyin:"qiān",         en:"thousand" },
    { zh:"铅笔",   pinyin:"qiānbǐ",       en:"pencil" },
    { zh:"清楚",   pinyin:"qīngchǔ",      en:"clear, distinct" },
    { zh:"请",     pinyin:"qǐng",         en:"please; to invite" },
    { zh:"让",     pinyin:"ràng",         en:"to let, to allow" },
    { zh:"日",     pinyin:"rì",           en:"day, sun" },
    { zh:"如果",   pinyin:"rúguǒ",        en:"if, in case" },
    { zh:"身体",   pinyin:"shēntǐ",       en:"body, health" },
    { zh:"生病",   pinyin:"shēng bìng",   en:"to get sick, to be ill" },
    { zh:"时间",   pinyin:"shíjiān",      en:"time" },
    { zh:"事情",   pinyin:"shìqing",      en:"matter, thing, affair" },
    { zh:"手表",   pinyin:"shǒubiǎo",     en:"watch, wristwatch" },
    { zh:"手机",   pinyin:"shǒujī",       en:"mobile phone" },
    { zh:"帅",     pinyin:"shuài",        en:"handsome" },
    { zh:"睡",     pinyin:"shuì",         en:"to sleep" },
    { zh:"送",     pinyin:"sòng",         en:"to give (a gift), to see off" },
    { zh:"虽然",   pinyin:"suīrán",       en:"although, even though" },
    { zh:"所以",   pinyin:"suǒyǐ",        en:"so, therefore" },
    { zh:"踢足球", pinyin:"tī zúqiú",     en:"to play football/soccer" },
    { zh:"题",     pinyin:"tí",           en:"question, problem, topic" },
    { zh:"跳舞",   pinyin:"tiào wǔ",      en:"to dance" },
    { zh:"外",     pinyin:"wài",          en:"outside, foreign" },
    { zh:"完",     pinyin:"wán",          en:"to finish, to be done" },
    { zh:"玩",     pinyin:"wán",          en:"to play, to have fun" },
    { zh:"晚上",   pinyin:"wǎnshang",     en:"evening, night" },
    { zh:"往",     pinyin:"wǎng",         en:"towards, in the direction of" },
    { zh:"为什么", pinyin:"wèi shénme",   en:"why" },
    { zh:"问",     pinyin:"wèn",          en:"to ask" },
    { zh:"问题",   pinyin:"wèntí",        en:"question, problem" },
    { zh:"西瓜",   pinyin:"xīguā",        en:"watermelon" },
    { zh:"希望",   pinyin:"xīwàng",       en:"to hope, hope" },
    { zh:"洗",     pinyin:"xǐ",           en:"to wash" },
    { zh:"喜欢",   pinyin:"xǐhuān",       en:"to like, to enjoy" },
    { zh:"先",     pinyin:"xiān",         en:"first, in advance" },
    { zh:"向",     pinyin:"xiàng",        en:"towards, facing" },
    { zh:"小时",   pinyin:"xiǎoshí",      en:"hour" },
    { zh:"写",     pinyin:"xiě",          en:"to write" },
    { zh:"新",     pinyin:"xīn",          en:"new" },
    { zh:"姓",     pinyin:"xìng",         en:"surname, to be surnamed" },
    { zh:"休息",   pinyin:"xiūxi",        en:"to rest" },
    { zh:"雪",     pinyin:"xuě",          en:"snow" },
    { zh:"颜色",   pinyin:"yánsè",        en:"color" },
    { zh:"眼睛",   pinyin:"yǎnjing",      en:"eye" },
    { zh:"要",     pinyin:"yào",          en:"to want; will; must" },
    { zh:"也",     pinyin:"yě",           en:"also, too" },
    { zh:"已经",   pinyin:"yǐjīng",       en:"already" },
    { zh:"一下",   pinyin:"yīxià",        en:"once, a moment" },
    { zh:"因为",   pinyin:"yīnwèi",       en:"because" },
    { zh:"用",     pinyin:"yòng",         en:"to use" },
    { zh:"游泳",   pinyin:"yóuyǒng",      en:"to swim" },
    { zh:"右边",   pinyin:"yòubiān",      en:"right side" },
    { zh:"鱼",     pinyin:"yú",           en:"fish" },
    { zh:"元",     pinyin:"yuán",         en:"yuan (RMB)" },
    { zh:"远",     pinyin:"yuǎn",         en:"far, distant" },
    { zh:"运动",   pinyin:"yùndòng",      en:"sport, exercise" },
    { zh:"再",     pinyin:"zài",          en:"again, once more" },
    { zh:"早上",   pinyin:"zǎoshang",     en:"morning (early)" },
    { zh:"丈夫",   pinyin:"zhàngfu",      en:"husband" },
    { zh:"找",     pinyin:"zhǎo",         en:"to look for, to find" },
    { zh:"着",     pinyin:"zhe",          en:"(ongoing action particle)" },
    { zh:"真",     pinyin:"zhēn",         en:"really, truly" },
    { zh:"正在",   pinyin:"zhèngzài",     en:"in the process of, -ing" },
    { zh:"知道",   pinyin:"zhīdào",       en:"to know" },
    { zh:"只",     pinyin:"zhǐ",          en:"only, just" },
    { zh:"中间",   pinyin:"zhōngjiān",    en:"middle, between" },
    { zh:"走",     pinyin:"zǒu",          en:"to walk, to leave" },
    { zh:"最",     pinyin:"zuì",          en:"most, -est (superlative)" },
    { zh:"左边",   pinyin:"zuǒbiān",      en:"left side" },
  ],

  3: [
    { zh:"阿姨",   pinyin:"āyí",          en:"aunt; middle-aged woman" },
    { zh:"啊",     pinyin:"a",            en:"(exclamation particle)" },
    { zh:"矮",     pinyin:"ǎi",           en:"short (height)" },
    { zh:"爱好",   pinyin:"àihào",        en:"hobby, interest" },
    { zh:"安静",   pinyin:"ānjìng",       en:"quiet, peaceful" },
    { zh:"把",     pinyin:"bǎ",           en:"(disposal preposition)" },
    { zh:"班",     pinyin:"bān",          en:"class, shift" },
    { zh:"搬",     pinyin:"bān",          en:"to move (objects/house)" },
    { zh:"半",     pinyin:"bàn",          en:"half" },
    { zh:"办法",   pinyin:"bànfǎ",        en:"method, way to do something" },
    { zh:"办公室", pinyin:"bàngōngshì",   en:"office" },
    { zh:"帮",     pinyin:"bāng",         en:"to help" },
    { zh:"包",     pinyin:"bāo",          en:"bag, package" },
    { zh:"饱",     pinyin:"bǎo",          en:"full (after eating)" },
    { zh:"北方",   pinyin:"běifāng",      en:"north, northern China" },
    { zh:"被",     pinyin:"bèi",          en:"(passive voice marker)" },
    { zh:"鼻子",   pinyin:"bízi",         en:"nose" },
    { zh:"必须",   pinyin:"bìxū",         en:"must, have to" },
    { zh:"变化",   pinyin:"biànhuà",      en:"change, transformation" },
    { zh:"表示",   pinyin:"biǎoshì",      en:"to express, to indicate" },
    { zh:"表演",   pinyin:"biǎoyǎn",      en:"performance, to perform" },
    { zh:"表扬",   pinyin:"biǎoyáng",     en:"to praise, to commend" },
    { zh:"冰箱",   pinyin:"bīngxiāng",    en:"refrigerator" },
    { zh:"不但",   pinyin:"bùdàn",        en:"not only" },
    { zh:"参加",   pinyin:"cānjiā",       en:"to participate, to attend" },
    { zh:"草",     pinyin:"cǎo",          en:"grass, plant" },
    { zh:"层",     pinyin:"céng",         en:"floor, layer, storey" },
    { zh:"差",     pinyin:"chà",          en:"to lack; poor (quality)" },
    { zh:"超市",   pinyin:"chāoshì",      en:"supermarket" },
    { zh:"成绩",   pinyin:"chéngjì",      en:"grade, result, achievement" },
    { zh:"城市",   pinyin:"chéngshì",     en:"city" },
    { zh:"迟到",   pinyin:"chídào",       en:"to be late, to arrive late" },
    { zh:"除了",   pinyin:"chúle",        en:"except, besides" },
    { zh:"春",     pinyin:"chūn",         en:"spring (season)" },
    { zh:"词语",   pinyin:"cíyǔ",         en:"word, term, phrase" },
    { zh:"聪明",   pinyin:"cōngmíng",     en:"smart, clever, intelligent" },
    { zh:"打扫",   pinyin:"dǎsǎo",        en:"to clean, to sweep" },
    { zh:"打算",   pinyin:"dǎsuàn",       en:"to plan, plan" },
    { zh:"带",     pinyin:"dài",          en:"to bring, to carry, to lead" },
    { zh:"当然",   pinyin:"dāngrán",      en:"of course, naturally" },
    { zh:"地",     pinyin:"de",           en:"(adverb particle)" },
    { zh:"地图",   pinyin:"dìtú",         en:"map" },
    { zh:"地铁",   pinyin:"dìtiě",        en:"subway, metro" },
    { zh:"地址",   pinyin:"dìzhǐ",        en:"address" },
    { zh:"电梯",   pinyin:"diàntī",       en:"elevator, lift" },
    { zh:"电子邮件",pinyin:"diànzǐ yóujiàn",en:"email" },
    { zh:"东",     pinyin:"dōng",         en:"east" },
    { zh:"冬",     pinyin:"dōng",         en:"winter" },
    { zh:"动物",   pinyin:"dòngwù",       en:"animal" },
    { zh:"段",     pinyin:"duàn",         en:"section, paragraph, period" },
    { zh:"锻炼",   pinyin:"duànliàn",     en:"to exercise, to work out" },
    { zh:"多么",   pinyin:"duōme",        en:"how, what (exclamatory)" },
    { zh:"耳朵",   pinyin:"ěrduo",        en:"ear" },
    { zh:"发现",   pinyin:"fāxiàn",       en:"to discover, to find out" },
    { zh:"方便",   pinyin:"fāngbiàn",     en:"convenient" },
    { zh:"放",     pinyin:"fàng",         en:"to put, to place, to release" },
    { zh:"放假",   pinyin:"fàng jià",     en:"to have a holiday/vacation" },
    { zh:"分",     pinyin:"fēn",          en:"minute; point; to divide" },
    { zh:"附近",   pinyin:"fùjìn",        en:"nearby, in the vicinity" },
    { zh:"复习",   pinyin:"fùxí",         en:"to review, to revise" },
    { zh:"干净",   pinyin:"gānjìng",      en:"clean, neat" },
    { zh:"感冒",   pinyin:"gǎnmào",       en:"cold (illness), to catch a cold" },
    { zh:"感兴趣", pinyin:"gǎn xìngqù",   en:"to be interested in" },
    { zh:"刚才",   pinyin:"gāngcái",      en:"just now, a moment ago" },
    { zh:"个子",   pinyin:"gèzi",         en:"height, stature" },
    { zh:"各",     pinyin:"gè",           en:"each, every (various)" },
    { zh:"更",     pinyin:"gèng",         en:"even more, still more" },
    { zh:"跟",     pinyin:"gēn",          en:"with, and; to follow" },
    { zh:"根据",   pinyin:"gēnjù",        en:"according to, based on" },
    { zh:"故事",   pinyin:"gùshi",        en:"story, tale" },
    { zh:"刮风",   pinyin:"guā fēng",     en:"to be windy" },
    { zh:"关",     pinyin:"guān",         en:"to close, to turn off" },
    { zh:"关系",   pinyin:"guānxi",       en:"relationship, connection" },
    { zh:"关心",   pinyin:"guānxīn",      en:"to care about, concern" },
    { zh:"国家",   pinyin:"guójiā",       en:"country, nation" },
    { zh:"过去",   pinyin:"guòqù",        en:"past, (to go) over there" },
    { zh:"害怕",   pinyin:"hàipà",        en:"to be afraid, to fear" },
    { zh:"黑板",   pinyin:"hēibǎn",       en:"blackboard" },
    { zh:"后来",   pinyin:"hòulái",       en:"afterwards, later" },
    { zh:"护照",   pinyin:"hùzhào",       en:"passport" },
    { zh:"花",     pinyin:"huā",          en:"flower; to spend" },
    { zh:"花园",   pinyin:"huāyuán",      en:"garden" },
    { zh:"画",     pinyin:"huà",          en:"to draw, picture" },
    { zh:"坏",     pinyin:"huài",         en:"bad, broken" },
    { zh:"换",     pinyin:"huàn",         en:"to change, to exchange" },
    { zh:"环境",   pinyin:"huánjìng",     en:"environment, surroundings" },
    { zh:"还",     pinyin:"huán",         en:"to return (something)" },
    { zh:"回答",   pinyin:"huídá",        en:"to answer, to reply" },
    { zh:"会议",   pinyin:"huìyì",        en:"meeting, conference" },
    { zh:"或者",   pinyin:"huòzhě",       en:"or (in statements)" },
    { zh:"极",     pinyin:"jí",           en:"extremely, pole" },
    { zh:"记得",   pinyin:"jìde",         en:"to remember" },
    { zh:"季节",   pinyin:"jìjié",        en:"season" },
    { zh:"检查",   pinyin:"jiǎnchá",      en:"to check, to examine" },
    { zh:"简单",   pinyin:"jiǎndān",      en:"simple, easy" },
    { zh:"见面",   pinyin:"jiàn miàn",    en:"to meet, to see someone" },
    { zh:"教",     pinyin:"jiāo",         en:"to teach" },
    { zh:"脚",     pinyin:"jiǎo",         en:"foot, leg" },
    { zh:"角",     pinyin:"jiǎo",         en:"jiao (10 cents); angle" },
    { zh:"接",     pinyin:"jiē",          en:"to receive, to pick up" },
    { zh:"结婚",   pinyin:"jié hūn",      en:"to get married" },
    { zh:"结束",   pinyin:"jiéshù",       en:"to end, to finish" },
    { zh:"经常",   pinyin:"jīngcháng",    en:"often, frequently" },
    { zh:"经过",   pinyin:"jīngguò",      en:"to pass by, to go through" },
    { zh:"经理",   pinyin:"jīnglǐ",       en:"manager, director" },
    { zh:"旧",     pinyin:"jiù",          en:"old, used, worn" },
    { zh:"举行",   pinyin:"jǔxíng",       en:"to hold (an event)" },
    { zh:"句子",   pinyin:"jùzi",         en:"sentence" },
    { zh:"决定",   pinyin:"juédìng",      en:"to decide, decision" },
    { zh:"可爱",   pinyin:"kě'ài",        en:"cute, lovable" },
    { zh:"渴",     pinyin:"kě",           en:"thirsty" },
    { zh:"哭",     pinyin:"kū",           en:"to cry, to weep" },
    { zh:"筷子",   pinyin:"kuàizi",       en:"chopsticks" },
    { zh:"历史",   pinyin:"lìshǐ",        en:"history" },
    { zh:"脸",     pinyin:"liǎn",         en:"face" },
    { zh:"练习",   pinyin:"liànxí",       en:"to practice, exercise" },
    { zh:"楼",     pinyin:"lóu",          en:"building, floor (storey)" },
    { zh:"绿",     pinyin:"lǜ",           en:"green" },
    { zh:"满意",   pinyin:"mǎnyì",        en:"satisfied, content" },
    { zh:"帽子",   pinyin:"màozi",        en:"hat, cap" },
    { zh:"明白",   pinyin:"míngbai",      en:"to understand, clear" },
    { zh:"拿",     pinyin:"ná",           en:"to take, to hold" },
    { zh:"奶奶",   pinyin:"nǎinai",       en:"grandma (paternal)" },
    { zh:"南",     pinyin:"nán",          en:"south" },
    { zh:"年级",   pinyin:"niánjí",       en:"grade, year (school)" },
    { zh:"努力",   pinyin:"nǔlì",         en:"to work hard, diligent" },
    { zh:"爬山",   pinyin:"pá shān",      en:"to hike, to climb a mountain" },
    { zh:"盘子",   pinyin:"pánzi",        en:"plate, dish" },
    { zh:"胖",     pinyin:"pàng",         en:"fat, overweight" },
    { zh:"跑",     pinyin:"pǎo",          en:"to run" },
    { zh:"啤酒",   pinyin:"píjiǔ",        en:"beer" },
    { zh:"瓶子",   pinyin:"píngzi",       en:"bottle" },
    { zh:"普通话", pinyin:"pǔtōnghuà",    en:"Mandarin Chinese" },
    { zh:"其实",   pinyin:"qíshí",        en:"actually, in fact" },
    { zh:"其他",   pinyin:"qítā",         en:"other, the rest" },
    { zh:"奇怪",   pinyin:"qíguài",       en:"strange, odd" },
    { zh:"铅笔",   pinyin:"qiānbǐ",       en:"pencil" },
    { zh:"墙",     pinyin:"qiáng",        en:"wall" },
    { zh:"亲戚",   pinyin:"qīnqi",        en:"relative (family)" },
    { zh:"轻",     pinyin:"qīng",         en:"light (weight)" },
    { zh:"请假",   pinyin:"qǐng jià",     en:"to ask for leave" },
    { zh:"秋",     pinyin:"qiū",          en:"autumn, fall" },
    { zh:"裙子",   pinyin:"qúnzi",        en:"skirt, dress" },
    { zh:"然后",   pinyin:"ránhòu",       en:"then, after that" },
    { zh:"热情",   pinyin:"rèqíng",       en:"enthusiastic, warm" },
    { zh:"认为",   pinyin:"rènwéi",       en:"to think, to believe" },
    { zh:"扔",     pinyin:"rēng",         en:"to throw, to toss" },
    { zh:"上网",   pinyin:"shàng wǎng",   en:"to go online, to surf the internet" },
    { zh:"社会",   pinyin:"shèhuì",       en:"society" },
    { zh:"生气",   pinyin:"shēngqì",      en:"to be angry" },
    { zh:"声音",   pinyin:"shēngyīn",     en:"sound, voice" },
    { zh:"使",     pinyin:"shǐ",          en:"to make, to cause" },
    { zh:"世界",   pinyin:"shìjiè",       en:"world" },
    { zh:"叔叔",   pinyin:"shūshu",       en:"uncle (paternal)" },
    { zh:"树",     pinyin:"shù",          en:"tree" },
    { zh:"数学",   pinyin:"shùxué",       en:"mathematics, math" },
    { zh:"双",     pinyin:"shuāng",       en:"pair, double" },
    { zh:"水平",   pinyin:"shuǐpíng",     en:"level, standard" },
    { zh:"司机",   pinyin:"sījī",         en:"driver" },
    { zh:"太阳",   pinyin:"tàiyáng",      en:"sun" },
    { zh:"特别",   pinyin:"tèbié",        en:"special, especially" },
    { zh:"提高",   pinyin:"tígāo",        en:"to improve, to raise" },
    { zh:"甜",     pinyin:"tián",         en:"sweet" },
    { zh:"条",     pinyin:"tiáo",         en:"(measure word for long things)" },
    { zh:"同事",   pinyin:"tóngshì",      en:"colleague, coworker" },
    { zh:"同意",   pinyin:"tóngyì",       en:"to agree, to consent" },
    { zh:"突然",   pinyin:"tūrán",        en:"sudden, suddenly" },
    { zh:"图书馆", pinyin:"túshūguǎn",    en:"library" },
    { zh:"腿",     pinyin:"tuǐ",          en:"leg" },
    { zh:"完成",   pinyin:"wánchéng",     en:"to complete, to accomplish" },
    { zh:"网站",   pinyin:"wǎngzhàn",     en:"website" },
    { zh:"忘记",   pinyin:"wàngjì",       en:"to forget" },
    { zh:"西",     pinyin:"xī",           en:"west" },
    { zh:"夏",     pinyin:"xià",          en:"summer" },
    { zh:"相同",   pinyin:"xiāngtóng",    en:"same, identical" },
    { zh:"香蕉",   pinyin:"xiāngjiāo",    en:"banana" },
    { zh:"像",     pinyin:"xiàng",        en:"to resemble, like" },
    { zh:"小说",   pinyin:"xiǎoshuō",     en:"novel, fiction" },
    { zh:"笑",     pinyin:"xiào",         en:"to laugh, to smile" },
    { zh:"信",     pinyin:"xìn",          en:"letter; to believe" },
    { zh:"兴趣",   pinyin:"xìngqù",       en:"interest, hobby" },
    { zh:"熊猫",   pinyin:"xióngmāo",     en:"panda" },
    { zh:"需要",   pinyin:"xūyào",        en:"to need, to require" },
    { zh:"选择",   pinyin:"xuǎnzé",       en:"to choose, choice" },
    { zh:"也许",   pinyin:"yěxǔ",         en:"perhaps, maybe" },
    { zh:"一定",   pinyin:"yīdìng",       en:"certainly, definitely" },
    { zh:"一共",   pinyin:"yīgòng",       en:"in total, altogether" },
    { zh:"一样",   pinyin:"yīyàng",       en:"same, alike" },
    { zh:"一般",   pinyin:"yībān",        en:"ordinary, generally" },
    { zh:"一直",   pinyin:"yīzhí",        en:"all along, continuously" },
    { zh:"音乐",   pinyin:"yīnyuè",       en:"music" },
    { zh:"银行",   pinyin:"yínháng",      en:"bank" },
    { zh:"影响",   pinyin:"yǐngxiǎng",    en:"influence, to affect" },
    { zh:"应该",   pinyin:"yīnggāi",      en:"should, ought to" },
    { zh:"邮局",   pinyin:"yóujú",        en:"post office" },
    { zh:"有名",   pinyin:"yǒumíng",      en:"famous, well-known" },
    { zh:"语言",   pinyin:"yǔyán",        en:"language" },
    { zh:"愿意",   pinyin:"yuànyì",       en:"willing, to be willing to" },
    { zh:"越",     pinyin:"yuè",          en:"the more…the more…" },
    { zh:"站",     pinyin:"zhàn",         en:"station, stop; to stand" },
    { zh:"张",     pinyin:"zhāng",        en:"(measure word for flat objects)" },
    { zh:"长",     pinyin:"zhǎng",        en:"to grow; senior" },
    { zh:"着急",   pinyin:"zháojí",       en:"anxious, worried" },
    { zh:"只有",   pinyin:"zhǐyǒu",       en:"only if, only when" },
    { zh:"中文",   pinyin:"Zhōngwén",     en:"Chinese (written language)" },
    { zh:"重要",   pinyin:"zhòngyào",     en:"important" },
    { zh:"主要",   pinyin:"zhǔyào",       en:"main, major, primary" },
    { zh:"注意",   pinyin:"zhùyì",        en:"to pay attention, to notice" },
    { zh:"准备",   pinyin:"zhǔnbèi",      en:"to prepare, preparation" },
    { zh:"自己",   pinyin:"zìjǐ",         en:"oneself, self" },
    { zh:"总是",   pinyin:"zǒngshì",      en:"always" },
    { zh:"嘴",     pinyin:"zuǐ",          en:"mouth" },
    { zh:"最后",   pinyin:"zuìhòu",       en:"finally, last" },
    { zh:"最近",   pinyin:"zuìjìn",       en:"recently, lately" },
  ],

  4: [
    { zh:"爱情",   pinyin:"àiqíng",       en:"love, romance" },
    { zh:"安排",   pinyin:"ānpái",        en:"to arrange, arrangement" },
    { zh:"按照",   pinyin:"ànzhào",       en:"according to, in accordance with" },
    { zh:"保护",   pinyin:"bǎohù",        en:"to protect, protection" },
    { zh:"报告",   pinyin:"bàogào",       en:"report, to report" },
    { zh:"比较",   pinyin:"bǐjiào",       en:"to compare; relatively" },
    { zh:"表达",   pinyin:"biǎodá",       en:"to express, expression" },
    { zh:"标准",   pinyin:"biāozhǔn",     en:"standard, criterion" },
    { zh:"不得不", pinyin:"bùdébù",       en:"have to, cannot but" },
    { zh:"不管",   pinyin:"bùguǎn",       en:"no matter, regardless" },
    { zh:"不仅",   pinyin:"bùjǐn",        en:"not only" },
    { zh:"材料",   pinyin:"cáiliào",      en:"material, data" },
    { zh:"产品",   pinyin:"chǎnpǐn",      en:"product" },
    { zh:"吵",     pinyin:"chǎo",         en:"noisy; to quarrel" },
    { zh:"成功",   pinyin:"chénggōng",    en:"to succeed, success" },
    { zh:"乘坐",   pinyin:"chéngzuò",     en:"to ride, to travel by" },
    { zh:"重新",   pinyin:"chóngxīn",     en:"again, anew" },
    { zh:"出发",   pinyin:"chūfā",        en:"to set off, to depart" },
    { zh:"传统",   pinyin:"chuántǒng",    en:"tradition, traditional" },
    { zh:"此外",   pinyin:"cǐwài",        en:"besides, in addition" },
    { zh:"从来",   pinyin:"cónglái",      en:"always, at all times" },
    { zh:"打折",   pinyin:"dǎ zhé",       en:"to discount, on sale" },
    { zh:"担心",   pinyin:"dānxīn",       en:"to worry, to be worried" },
    { zh:"导游",   pinyin:"dǎoyóu",       en:"tour guide" },
    { zh:"道歉",   pinyin:"dào qiàn",     en:"to apologize" },
    { zh:"得意",   pinyin:"déyì",         en:"proud, pleased with oneself" },
    { zh:"登机牌", pinyin:"dēngjī pái",   en:"boarding pass" },
    { zh:"地球",   pinyin:"dìqiú",        en:"Earth, the globe" },
    { zh:"队",     pinyin:"duì",          en:"team, queue" },
    { zh:"对话",   pinyin:"duìhuà",       en:"dialogue, conversation" },
    { zh:"发展",   pinyin:"fāzhǎn",       en:"to develop, development" },
    { zh:"翻译",   pinyin:"fānyì",        en:"to translate, translator" },
    { zh:"方向",   pinyin:"fāngxiàng",    en:"direction, orientation" },
    { zh:"丰富",   pinyin:"fēngfù",       en:"rich, abundant" },
    { zh:"否则",   pinyin:"fǒuzé",        en:"otherwise, if not" },
    { zh:"符合",   pinyin:"fúhé",         en:"to conform to, to match" },
    { zh:"复杂",   pinyin:"fùzá",         en:"complex, complicated" },
    { zh:"感动",   pinyin:"gǎndòng",      en:"to be moved/touched" },
    { zh:"感激",   pinyin:"gǎnjī",        en:"grateful, thankful" },
    { zh:"各种",   pinyin:"gèzhǒng",      en:"various kinds of" },
    { zh:"公里",   pinyin:"gōnglǐ",       en:"kilometer" },
    { zh:"购物",   pinyin:"gòuwù",        en:"to shop, shopping" },
    { zh:"规定",   pinyin:"guīdìng",      en:"rule, regulation; to stipulate" },
    { zh:"过敏",   pinyin:"guòmǐn",       en:"allergy, to be allergic" },
    { zh:"号码",   pinyin:"hàomǎ",        en:"number (telephone, etc.)" },
    { zh:"合适",   pinyin:"héshì",        en:"suitable, appropriate" },
    { zh:"互联网", pinyin:"hùliánwǎng",   en:"internet" },
    { zh:"互相",   pinyin:"hùxiāng",      en:"each other, mutually" },
    { zh:"积极",   pinyin:"jījí",         en:"positive, active, enthusiastic" },
    { zh:"即使",   pinyin:"jíshǐ",        en:"even if, even though" },
    { zh:"继续",   pinyin:"jìxù",         en:"to continue" },
    { zh:"价格",   pinyin:"jiàgé",        en:"price" },
    { zh:"减少",   pinyin:"jiǎnshǎo",     en:"to reduce, to decrease" },
    { zh:"建议",   pinyin:"jiànyì",       en:"suggestion; to suggest" },
    { zh:"将来",   pinyin:"jiānglái",     en:"future, in the future" },
    { zh:"交通",   pinyin:"jiāotōng",     en:"traffic, transportation" },
    { zh:"交流",   pinyin:"jiāoliú",      en:"to exchange, communication" },
    { zh:"节日",   pinyin:"jiérì",        en:"holiday, festival" },
    { zh:"接受",   pinyin:"jiēshòu",      en:"to accept, to receive" },
    { zh:"解决",   pinyin:"jiějué",       en:"to solve, to resolve" },
    { zh:"紧张",   pinyin:"jǐnzhāng",     en:"nervous, tense" },
    { zh:"进行",   pinyin:"jìnxíng",      en:"to carry out, to conduct" },
    { zh:"进步",   pinyin:"jìnbù",        en:"progress, to make progress" },
    { zh:"精彩",   pinyin:"jīngcǎi",      en:"wonderful, brilliant" },
    { zh:"竟然",   pinyin:"jìngrán",      en:"unexpectedly, to one's surprise" },
    { zh:"尽管",   pinyin:"jǐnguǎn",      en:"despite, even though" },
    { zh:"经济",   pinyin:"jīngjì",       en:"economy, economic" },
    { zh:"举",     pinyin:"jǔ",           en:"to lift, to raise" },
    { zh:"拒绝",   pinyin:"jùjué",        en:"to refuse, to decline" },
    { zh:"开玩笑", pinyin:"kāi wánxiào",  en:"to joke, to kid around" },
    { zh:"看法",   pinyin:"kànfǎ",        en:"view, opinion" },
    { zh:"烤",     pinyin:"kǎo",          en:"to bake, to roast" },
    { zh:"科学",   pinyin:"kēxué",        en:"science" },
    { zh:"肯定",   pinyin:"kěndìng",      en:"certainly; to affirm" },
    { zh:"空气",   pinyin:"kōngqì",       en:"air" },
    { zh:"来不及", pinyin:"láibují",      en:"not have time, too late" },
    { zh:"来得及", pinyin:"láidejí",      en:"there's still time, to make it" },
    { zh:"礼貌",   pinyin:"lǐmào",        en:"polite, politeness" },
    { zh:"理解",   pinyin:"lǐjiě",        en:"to understand, comprehension" },
    { zh:"联系",   pinyin:"liánxì",       en:"to contact, connection" },
    { zh:"留",     pinyin:"liú",          en:"to keep, to stay, to leave" },
    { zh:"旅行",   pinyin:"lǚxíng",       en:"to travel, trip" },
    { zh:"律师",   pinyin:"lǜshī",        en:"lawyer" },
    { zh:"麻烦",   pinyin:"máfan",        en:"troublesome; trouble" },
    { zh:"目的",   pinyin:"mùdì",         en:"purpose, goal" },
    { zh:"难道",   pinyin:"nándào",       en:"could it be that, don't tell me" },
    { zh:"内容",   pinyin:"nèiróng",      en:"content, substance" },
    { zh:"能力",   pinyin:"nénglì",       en:"ability, capability" },
    { zh:"年轻",   pinyin:"niánqīng",     en:"young" },
    { zh:"皮肤",   pinyin:"pífū",         en:"skin" },
    { zh:"其中",   pinyin:"qízhōng",      en:"among them, within" },
    { zh:"起来",   pinyin:"qǐlai",        en:"to get up; (start of action)" },
    { zh:"气候",   pinyin:"qìhòu",        en:"climate" },
    { zh:"千万",   pinyin:"qiānwàn",      en:"by all means, ten million" },
    { zh:"缺点",   pinyin:"quēdiǎn",      en:"shortcoming, weakness" },
    { zh:"确实",   pinyin:"quèshí",       en:"indeed, really" },
    { zh:"热闹",   pinyin:"rènao",        en:"lively, bustling" },
    { zh:"认真",   pinyin:"rènzhēn",      en:"serious, earnest, careful" },
    { zh:"任何",   pinyin:"rènhé",        en:"any, whatever" },
    { zh:"入口",   pinyin:"rùkǒu",        en:"entrance" },
    { zh:"散步",   pinyin:"sàn bù",       en:"to take a walk" },
    { zh:"上当",   pinyin:"shàng dàng",   en:"to be fooled, to be tricked" },
    { zh:"深",     pinyin:"shēn",         en:"deep, profound" },
    { zh:"省",     pinyin:"shěng",        en:"province; to save" },
    { zh:"生命",   pinyin:"shēngmìng",    en:"life" },
    { zh:"师傅",   pinyin:"shīfu",        en:"master, skilled worker" },
    { zh:"实际",   pinyin:"shíjì",        en:"practical, actual" },
    { zh:"失败",   pinyin:"shībài",       en:"to fail, failure" },
    { zh:"顺序",   pinyin:"shùnxù",       en:"order, sequence" },
    { zh:"随着",   pinyin:"suízhe",       en:"along with, following" },
    { zh:"态度",   pinyin:"tàidu",        en:"attitude" },
    { zh:"谈",     pinyin:"tán",          en:"to talk, to discuss" },
    { zh:"糖",     pinyin:"táng",         en:"sugar, candy" },
    { zh:"通过",   pinyin:"tōngguò",      en:"to pass through; by means of" },
    { zh:"同情",   pinyin:"tóngqíng",     en:"sympathy, to sympathize" },
    { zh:"推",     pinyin:"tuī",          en:"to push" },
    { zh:"推迟",   pinyin:"tuīchí",       en:"to postpone, to delay" },
    { zh:"万一",   pinyin:"wànyī",        en:"just in case, if by any chance" },
    { zh:"危险",   pinyin:"wēixiǎn",      en:"danger, dangerous" },
    { zh:"温度",   pinyin:"wēndù",        en:"temperature" },
    { zh:"文化",   pinyin:"wénhuà",       en:"culture" },
    { zh:"无论",   pinyin:"wúlùn",        en:"regardless of, no matter" },
    { zh:"西方",   pinyin:"xīfāng",       en:"the West, western" },
    { zh:"吸引",   pinyin:"xīyǐn",        en:"to attract, to draw" },
    { zh:"幸福",   pinyin:"xìngfú",       en:"happiness, happy" },
    { zh:"性格",   pinyin:"xìnggé",       en:"personality, character" },
    { zh:"修",     pinyin:"xiū",          en:"to repair, to fix" },
    { zh:"要求",   pinyin:"yāoqiú",       en:"to require, requirement" },
    { zh:"依然",   pinyin:"yīrán",        en:"still, as before" },
    { zh:"意见",   pinyin:"yìjiàn",       en:"opinion, objection" },
    { zh:"因此",   pinyin:"yīncǐ",        en:"therefore, as a result" },
    { zh:"以为",   pinyin:"yǐwéi",        en:"to think (mistakenly)" },
    { zh:"以",     pinyin:"yǐ",           en:"with, by means of" },
    { zh:"优点",   pinyin:"yōudiǎn",      en:"advantage, merit" },
    { zh:"由于",   pinyin:"yóuyú",        en:"due to, because of" },
    { zh:"于是",   pinyin:"yúshì",        en:"as a result, so" },
    { zh:"原来",   pinyin:"yuánlái",      en:"originally; it turns out" },
    { zh:"原因",   pinyin:"yuányīn",      en:"reason, cause" },
    { zh:"约会",   pinyin:"yuēhuì",       en:"date, appointment" },
    { zh:"增加",   pinyin:"zēngjiā",      en:"to increase, to add" },
    { zh:"照顾",   pinyin:"zhàogù",       en:"to take care of, to look after" },
    { zh:"整理",   pinyin:"zhěnglǐ",      en:"to tidy up, to organize" },
    { zh:"只好",   pinyin:"zhǐhǎo",       en:"have to, can only" },
    { zh:"直接",   pinyin:"zhíjiē",       en:"direct, directly" },
    { zh:"终于",   pinyin:"zhōngyú",      en:"finally, at last" },
    { zh:"重",     pinyin:"zhòng",        en:"heavy; important" },
    { zh:"周围",   pinyin:"zhōuwéi",      en:"surroundings, around" },
    { zh:"主意",   pinyin:"zhǔyi",        en:"idea, plan" },
    { zh:"专门",   pinyin:"zhuānmén",     en:"special, specialized" },
    { zh:"赚",     pinyin:"zhuàn",        en:"to earn, to make money" },
    { zh:"自然",   pinyin:"zìrán",        en:"nature, natural" },
    { zh:"总结",   pinyin:"zǒngjié",      en:"to summarize, summary" },
    { zh:"尊重",   pinyin:"zūnzhòng",     en:"to respect, respect" },
  ],

  5: [
    { zh:"版本",   pinyin:"bǎnběn",       en:"version, edition" },
    { zh:"保持",   pinyin:"bǎochí",       en:"to maintain, to keep" },
    { zh:"保证",   pinyin:"bǎozhèng",     en:"to guarantee, guarantee" },
    { zh:"背景",   pinyin:"bèijǐng",      en:"background, backdrop" },
    { zh:"本质",   pinyin:"běnzhì",       en:"nature, essence" },
    { zh:"必要",   pinyin:"bìyào",        en:"necessary, essential" },
    { zh:"不断",   pinyin:"bùduàn",       en:"continuously, unceasingly" },
    { zh:"不得了", pinyin:"bùdéliǎo",     en:"terrible, extremely" },
    { zh:"采用",   pinyin:"cǎiyòng",      en:"to adopt, to use" },
    { zh:"参考",   pinyin:"cānkǎo",       en:"to refer to, reference" },
    { zh:"层次",   pinyin:"céngcì",       en:"level, layer, hierarchy" },
    { zh:"承认",   pinyin:"chéngrèn",     en:"to admit, to acknowledge" },
    { zh:"吃亏",   pinyin:"chī kuī",      en:"to suffer a loss, to be at a disadvantage" },
    { zh:"充分",   pinyin:"chōngfèn",     en:"fully, sufficient" },
    { zh:"抽象",   pinyin:"chōuxiàng",    en:"abstract" },
    { zh:"处理",   pinyin:"chǔlǐ",        en:"to handle, to deal with" },
    { zh:"此",     pinyin:"cǐ",           en:"this, here" },
    { zh:"刺激",   pinyin:"cìjī",         en:"to stimulate; exciting" },
    { zh:"存在",   pinyin:"cúnzài",       en:"to exist, existence" },
    { zh:"措施",   pinyin:"cuòshī",       en:"measure, step (action)" },
    { zh:"达到",   pinyin:"dádào",        en:"to achieve, to reach" },
    { zh:"代表",   pinyin:"dàibiǎo",      en:"representative; to represent" },
    { zh:"当地",   pinyin:"dāngdì",       en:"local, locally" },
    { zh:"当时",   pinyin:"dāngshí",      en:"at that time, then" },
    { zh:"道理",   pinyin:"dàolǐ",        en:"reason, principle, sense" },
    { zh:"得到",   pinyin:"dédào",        en:"to obtain, to get" },
    { zh:"典型",   pinyin:"diǎnxíng",     en:"typical, representative example" },
    { zh:"独立",   pinyin:"dúlì",         en:"independent, independence" },
    { zh:"对待",   pinyin:"duìdài",       en:"to treat, to deal with" },
    { zh:"多余",   pinyin:"duōyú",        en:"surplus, unnecessary" },
    { zh:"而",     pinyin:"ér",           en:"and, but, while (conjunction)" },
    { zh:"而且",   pinyin:"érqiě",        en:"furthermore, moreover" },
    { zh:"发挥",   pinyin:"fāhuī",        en:"to bring into play, to display" },
    { zh:"方案",   pinyin:"fāng'àn",      en:"plan, scheme, proposal" },
    { zh:"分析",   pinyin:"fēnxī",        en:"to analyze, analysis" },
    { zh:"否认",   pinyin:"fǒurèn",       en:"to deny, to negate" },
    { zh:"负责",   pinyin:"fùzé",         en:"to be responsible for" },
    { zh:"改革",   pinyin:"gǎigé",        en:"reform, to reform" },
    { zh:"改善",   pinyin:"gǎishàn",      en:"to improve, improvement" },
    { zh:"个人",   pinyin:"gèrén",        en:"individual, personal" },
    { zh:"观点",   pinyin:"guāndiǎn",     en:"viewpoint, standpoint" },
    { zh:"广大",   pinyin:"guǎngdà",      en:"vast, wide, extensive" },
    { zh:"规律",   pinyin:"guīlǜ",        en:"law, rule, pattern" },
    { zh:"过程",   pinyin:"guòchéng",     en:"process, course" },
    { zh:"后果",   pinyin:"hòuguǒ",       en:"consequence, aftermath" },
    { zh:"合理",   pinyin:"hélǐ",         en:"reasonable, rational" },
    { zh:"忽视",   pinyin:"hūshì",        en:"to ignore, to overlook" },
    { zh:"基本",   pinyin:"jīběn",        en:"basic, fundamental" },
    { zh:"基础",   pinyin:"jīchǔ",        en:"foundation, basis" },
    { zh:"激动",   pinyin:"jīdòng",       en:"excited, to excite" },
    { zh:"假设",   pinyin:"jiǎshè",       en:"hypothesis, to assume" },
    { zh:"坚持",   pinyin:"jiānchí",      en:"to persist, to insist" },
    { zh:"建立",   pinyin:"jiànlì",       en:"to establish, to found" },
    { zh:"角度",   pinyin:"jiǎodù",       en:"angle, perspective" },
    { zh:"结合",   pinyin:"jiéhé",        en:"to combine, combination" },
    { zh:"尽力",   pinyin:"jìnlì",        en:"to do one's best, to try hard" },
    { zh:"进一步", pinyin:"jìn yī bù",    en:"further, go a step further" },
    { zh:"据",     pinyin:"jù",           en:"according to, based on" },
    { zh:"均",     pinyin:"jūn",          en:"equal, all, without exception" },
    { zh:"客观",   pinyin:"kèguān",       en:"objective" },
    { zh:"来源",   pinyin:"láiyuán",      en:"source, origin" },
    { zh:"利用",   pinyin:"lìyòng",       en:"to use, to utilize" },
    { zh:"逻辑",   pinyin:"luójí",        en:"logic" },
    { zh:"满足",   pinyin:"mǎnzú",        en:"to satisfy, to be satisfied" },
    { zh:"矛盾",   pinyin:"máodùn",       en:"contradiction, conflict" },
    { zh:"明显",   pinyin:"míngxiǎn",     en:"obvious, evident" },
    { zh:"目标",   pinyin:"mùbiāo",       en:"goal, target, objective" },
    { zh:"难怪",   pinyin:"nánguài",      en:"no wonder, it's no surprise" },
    { zh:"能源",   pinyin:"néngyuán",     en:"energy (resource)" },
    { zh:"年代",   pinyin:"niándài",      en:"decade, era" },
    { zh:"判断",   pinyin:"pànduàn",      en:"to judge, judgment" },
    { zh:"培养",   pinyin:"péiyǎng",      en:"to cultivate, to train" },
    { zh:"评价",   pinyin:"píngjià",      en:"to evaluate, evaluation" },
    { zh:"破坏",   pinyin:"pòhuài",       en:"to destroy, to damage" },
    { zh:"起到",   pinyin:"qǐ dào",       en:"to play a role, to achieve" },
    { zh:"器官",   pinyin:"qìguān",       en:"organ (body)" },
    { zh:"强调",   pinyin:"qiángdiào",    en:"to emphasize, to stress" },
    { zh:"亲自",   pinyin:"qīnzì",        en:"personally, in person" },
    { zh:"确定",   pinyin:"quèdìng",      en:"to confirm, to determine" },
    { zh:"取得",   pinyin:"qǔdé",         en:"to obtain, to achieve" },
    { zh:"全面",   pinyin:"quánmiàn",     en:"comprehensive, all-around" },
    { zh:"缺乏",   pinyin:"quēfá",        en:"to lack, shortage of" },
    { zh:"认识",   pinyin:"rènshi",       en:"understanding, knowledge" },
    { zh:"任务",   pinyin:"rènwu",        en:"task, mission, assignment" },
    { zh:"如今",   pinyin:"rújīn",        en:"nowadays, now" },
    { zh:"弱",     pinyin:"ruò",          en:"weak, frail" },
    { zh:"深刻",   pinyin:"shēnkè",       en:"profound, deep" },
    { zh:"实现",   pinyin:"shíxiàn",      en:"to realize, to achieve" },
    { zh:"适合",   pinyin:"shìhé",        en:"to suit, to be suitable for" },
    { zh:"手段",   pinyin:"shǒuduàn",     en:"method, means, measure" },
    { zh:"水平",   pinyin:"shuǐpíng",     en:"level, standard" },
    { zh:"说明",   pinyin:"shuōmíng",     en:"to explain, explanation" },
    { zh:"思想",   pinyin:"sīxiǎng",      en:"thought, ideology, thinking" },
    { zh:"速度",   pinyin:"sùdù",         en:"speed, velocity" },
    { zh:"损失",   pinyin:"sǔnshī",       en:"loss, damage" },
    { zh:"所谓",   pinyin:"suǒwèi",       en:"so-called" },
    { zh:"探讨",   pinyin:"tàntǎo",       en:"to explore, to discuss" },
    { zh:"提供",   pinyin:"tígōng",       en:"to provide, to supply" },
    { zh:"体现",   pinyin:"tǐxiàn",       en:"to embody, to reflect" },
    { zh:"条件",   pinyin:"tiáojiàn",     en:"condition, requirement" },
    { zh:"途径",   pinyin:"tújìng",       en:"way, channel, approach" },
    { zh:"推动",   pinyin:"tuīdòng",      en:"to promote, to drive forward" },
    { zh:"完善",   pinyin:"wánshàn",      en:"to perfect, to improve" },
    { zh:"为了",   pinyin:"wèile",        en:"in order to, for the sake of" },
    { zh:"维护",   pinyin:"wéihù",        en:"to maintain, to protect" },
    { zh:"相比",   pinyin:"xiāng bǐ",     en:"compared to, in comparison" },
    { zh:"相对",   pinyin:"xiāngduì",     en:"relatively, compared to" },
    { zh:"相互",   pinyin:"xiānghù",      en:"mutual, each other" },
    { zh:"消极",   pinyin:"xiāojí",       en:"negative, passive" },
    { zh:"形成",   pinyin:"xíngchéng",    en:"to form, to take shape" },
    { zh:"形象",   pinyin:"xíngxiàng",    en:"image, form, figure" },
    { zh:"虽",     pinyin:"suī",          en:"although, even though" },
    { zh:"严格",   pinyin:"yángé",        en:"strict, rigorous" },
    { zh:"严重",   pinyin:"yánzhòng",     en:"serious, severe" },
    { zh:"研究",   pinyin:"yánjiū",       en:"to research, research" },
    { zh:"一旦",   pinyin:"yīdàn",        en:"once, in case" },
    { zh:"意义",   pinyin:"yìyì",         en:"meaning, significance" },
    { zh:"以来",   pinyin:"yǐlái",        en:"since (a time)" },
    { zh:"引起",   pinyin:"yǐnqǐ",        en:"to cause, to give rise to" },
    { zh:"优势",   pinyin:"yōushì",       en:"advantage, superiority" },
    { zh:"有效",   pinyin:"yǒuxiào",      en:"effective, valid" },
    { zh:"预期",   pinyin:"yùqī",         en:"expected, anticipated" },
    { zh:"运用",   pinyin:"yùnyòng",      en:"to apply, to use" },
    { zh:"在于",   pinyin:"zàiyú",        en:"to lie in, to rest with" },
    { zh:"展示",   pinyin:"zhǎnshì",      en:"to show, to display" },
    { zh:"正确",   pinyin:"zhèngquè",     en:"correct, right" },
    { zh:"支持",   pinyin:"zhīchí",       en:"to support, support" },
    { zh:"制度",   pinyin:"zhìdù",        en:"system, institution" },
    { zh:"重视",   pinyin:"zhòngshì",     en:"to attach importance to" },
    { zh:"主观",   pinyin:"zhǔguān",      en:"subjective" },
    { zh:"主张",   pinyin:"zhǔzhāng",     en:"to advocate, position, claim" },
    { zh:"资源",   pinyin:"zīyuán",       en:"resources" },
    { zh:"综合",   pinyin:"zōnghé",       en:"comprehensive, to synthesize" },
  ],

  6: [
    { zh:"辩证",   pinyin:"biànzhèng",    en:"dialectical" },
    { zh:"层面",   pinyin:"céngmiàn",     en:"aspect, dimension, level" },
    { zh:"阐述",   pinyin:"chǎnshù",      en:"to elaborate, to expound" },
    { zh:"彻底",   pinyin:"chèdǐ",        en:"thorough, completely" },
    { zh:"承担",   pinyin:"chéngdān",     en:"to bear, to undertake" },
    { zh:"持续",   pinyin:"chíxù",        en:"to continue, to sustain" },
    { zh:"抽样",   pinyin:"chōuyàng",     en:"sampling, to sample" },
    { zh:"创新",   pinyin:"chuàngxīn",    en:"innovation, to innovate" },
    { zh:"错综",   pinyin:"cuòzōng",      en:"complex, intricate" },
    { zh:"当务之急",pinyin:"dāng wù zhī jí",en:"most urgent task" },
    { zh:"道德",   pinyin:"dàodé",        en:"morality, ethics" },
    { zh:"等等",   pinyin:"děngděng",     en:"and so on, et cetera" },
    { zh:"理论",   pinyin:"lǐlùn",        en:"theory" },
    { zh:"典故",   pinyin:"diǎngù",       en:"allusion, literary reference" },
    { zh:"动态",   pinyin:"dòngtài",      en:"dynamic, trend, movement" },
    { zh:"对比",   pinyin:"duìbǐ",        en:"contrast, to compare" },
    { zh:"多元",   pinyin:"duōyuán",      en:"pluralistic, diverse" },
    { zh:"发挥",   pinyin:"fāhuī",        en:"to play a role, to give full expression" },
    { zh:"繁荣",   pinyin:"fánróng",      en:"prosperous, flourishing" },
    { zh:"方针",   pinyin:"fāngzhēn",     en:"policy, guiding principle" },
    { zh:"范畴",   pinyin:"fànchóu",      en:"category, scope" },
    { zh:"丰厚",   pinyin:"fēnghòu",      en:"generous, rich, abundant" },
    { zh:"概念",   pinyin:"gàiniàn",      en:"concept, notion" },
    { zh:"格局",   pinyin:"géjú",         en:"pattern, structure, situation" },
    { zh:"构成",   pinyin:"gòuchéng",     en:"to constitute, to form" },
    { zh:"固然",   pinyin:"gùrán",        en:"admittedly, it is true that" },
    { zh:"归纳",   pinyin:"guīnà",        en:"to summarize, induction" },
    { zh:"规范",   pinyin:"guīfàn",       en:"standard, norm; to standardize" },
    { zh:"涵盖",   pinyin:"hángài",       en:"to encompass, to cover" },
    { zh:"和谐",   pinyin:"héxié",        en:"harmonious, harmony" },
    { zh:"宏观",   pinyin:"hóngguān",     en:"macroscopic, macro" },
    { zh:"核心",   pinyin:"héxīn",        en:"core, nucleus, heart of" },
    { zh:"假设",   pinyin:"jiǎshè",       en:"to hypothesize, hypothesis" },
    { zh:"价值观", pinyin:"jiàzhíguān",   en:"values, value system" },
    { zh:"建构",   pinyin:"jiàngòu",      en:"to construct, to build" },
    { zh:"渐渐",   pinyin:"jiànjiàn",     en:"gradually, by degrees" },
    { zh:"客观性", pinyin:"kèguānxìng",   en:"objectivity" },
    { zh:"框架",   pinyin:"kuàngjià",     en:"framework, structure" },
    { zh:"理性",   pinyin:"lǐxìng",       en:"reason, rationality" },
    { zh:"逻辑性", pinyin:"luójíxìng",    en:"logical consistency" },
    { zh:"论证",   pinyin:"lùnzhèng",     en:"to demonstrate, to argue" },
    { zh:"内涵",   pinyin:"nèihán",       en:"connotation, meaning, depth" },
    { zh:"凝聚",   pinyin:"níngjù",       en:"to condense, to rally" },
    { zh:"普遍",   pinyin:"pǔbiàn",       en:"universal, widespread" },
    { zh:"批判",   pinyin:"pīpàn",        en:"to criticize, criticism" },
    { zh:"取向",   pinyin:"qǔxiàng",      en:"orientation, tendency" },
    { zh:"趋势",   pinyin:"qūshì",        en:"trend, tendency" },
    { zh:"诠释",   pinyin:"quánshì",      en:"to interpret, interpretation" },
    { zh:"融合",   pinyin:"rónghé",       en:"to blend, to integrate" },
    { zh:"深层",   pinyin:"shēncéng",     en:"deep-level, underlying" },
    { zh:"渗透",   pinyin:"shèntòu",      en:"to permeate, to infiltrate" },
    { zh:"视角",   pinyin:"shìjiǎo",      en:"perspective, viewpoint, angle" },
    { zh:"塑造",   pinyin:"sùzào",        en:"to shape, to mold" },
    { zh:"贯穿",   pinyin:"guànchuān",    en:"to run through, to penetrate" },
    { zh:"推断",   pinyin:"tuīduàn",      en:"to infer, inference" },
    { zh:"系统",   pinyin:"xìtǒng",       en:"system, systematic" },
    { zh:"相辅相成",pinyin:"xiāng fǔ xiāng chéng",en:"to complement each other" },
    { zh:"形而上",  pinyin:"xíng ér shàng", en:"metaphysical, abstract" },
    { zh:"形势",   pinyin:"xíngshì",      en:"situation, circumstances" },
    { zh:"延伸",   pinyin:"yánshēn",      en:"to extend, to stretch" },
    { zh:"演变",   pinyin:"yǎnbiàn",      en:"to evolve, evolution" },
    { zh:"依据",   pinyin:"yījù",         en:"basis, according to" },
    { zh:"异同",   pinyin:"yìtóng",       en:"similarities and differences" },
    { zh:"因素",   pinyin:"yīnsù",        en:"factor, element" },
    { zh:"影射",   pinyin:"yǐngshè",      en:"to allude to, to insinuate" },
    { zh:"赋予",   pinyin:"fùyǔ",         en:"to endow, to give" },
    { zh:"主导",   pinyin:"zhǔdǎo",       en:"dominant, to dominate" },
    { zh:"主流",   pinyin:"zhǔliú",       en:"mainstream" },
    { zh:"转化",   pinyin:"zhuǎnhuà",     en:"to transform, transformation" },
    { zh:"自觉",   pinyin:"zìjué",        en:"conscious, self-aware" },
    { zh:"综述",   pinyin:"zōngshù",      en:"overview, comprehensive review" },
  ],
};

// Word counts per level
const HSK_COUNTS = Object.fromEntries(
  Object.entries(HSK_DATA).map(([lvl, words]) => [lvl, words.length])
);

// Fast lookup: Chinese characters → HSK level (integer 1–6, or undefined if not found)
const HSK_LOOKUP = {};
Object.entries(HSK_DATA).forEach(([lvl, words]) => {
  words.forEach(w => { HSK_LOOKUP[w.zh] = parseInt(lvl); });
});
